### ISSUE TITLE
Play/Pause button doesn't work with Kodi v18

### ISSUE THREAD

**Issue by jaylinski** [jaylinski/kodi-echo#5]
```
WebSocketApi.js:78 Socket send 105 Player.PlayPause (2) [1, "toggle"]0: 11: "toggle"length: 2__proto__: Array(0)
WebSocketApi.js:22 Socket recv 105 undefined {error: {…}, id: 105, jsonrpc: "2.0"}error: code: -32100message: "Failed to execute method."__proto__: Objectid: 105jsonrpc: "2.0"__proto__: Object
WebSocketApi.js:88 Uncaught (in promise) Error: {"code":-32100,"message":"Failed to execute method."}
    at EventTarget.handler (WebSocketApi.js:88)
    at WebSocket.socket.onmessage (WebSocketApi.js:23)
handler @ WebSocketApi.js:88
socket.onmessage @ WebSocketApi.js:23
async function (async)
playPause @ Kodi.js:116
pause @ Store.js:35
handleEvent @ parts.js:419
EventPart._boundHandleEvent @ parts.js:385
```

**Comment by jaylinski** [comment]
Chorus in Kodi v18.2 has the exact same issue. The sent payload:
```
[{"jsonrpc":"2.0","method":"Player.PlayPause","params":[1,"toggle"],"id":8}]
```
Play/Pause works with normal music, but fails if a Radio (https://kodi.wiki/view/Add-on:Radio) is playing or a TV stream (https://kodi.wiki/view/Add-on:IPTV_Simple_Client) is playing.

**Comment by kekukui** [comment]
I believe that **pause** is not a supported action on live stream links which are sent directly to Kodi's media player. **_It only works when a link is passed to the YouTube app_**.  But you can send menu navigation commands `(up/down/left/right)` `(enter/ok)` as demonstrated by this extension:

![image](https://user-images.githubusercontent.com/20834957/60242211-21fedf80-9883-11e9-9f1e-bad68f9d05ed.png)

https://github.com/regseb/castkodi
https://addons.mozilla.org/en-US/firefox/addon/castkodi
___________________

You can also use the **Fullscreen Toggle** (👁️) as demonstrated here:

![image](https://user-images.githubusercontent.com/20834957/60243030-4eb3f680-9885-11e9-8f96-6375f483125c.png)

https://github.com/LendoK/kodi-control
https://addons.mozilla.org/en-US/firefox/addon/kodi-control/
